boot.o: boot.S multiboot.h x86_desc.h types.h
idt_ref.o: idt_ref.S idt.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c
rtc.o: rtc.c i8259.h types.h rtc.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
